services:
  db:
    image: mysql:9.5
    container_name: mysql-foodtrace-db
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    volumes:
        - mysql-foodtrace-data:/var/lib/mysql
  redis: 
    image: redis:latest
    container_name: redis-foodchain-backend
    ports:
      - '6379:6379'

volumes:
  mysql-foodtrace-data: